<?php


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\DetallesComprasController;
use App\Http\Controllers\LocalizaArticuloController;
use App\Http\Controllers\LocalizarFrController;
use App\Http\Controllers\Api\EmpleadosController;
use App\Http\Controllers\Api\DespachoController;
use App\Http\Controllers\Api\ProveedoresController;
use App\Http\Controllers\Api\GruposController;
use App\Http\Controllers\Api\SubGruposController;
use App\Http\Controllers\Api\ColoresController;
use App\Http\Controllers\Api\VistaArticulosController;
use App\Http\Controllers\Api\SolicitudCompraController;
use App\Http\Controllers\Api\TipoSolicitudesController;
use App\Http\Controllers\Api\LocalizacionController;
use App\Http\Controllers\Api\DepositosController;
use App\Http\Controllers\Api\ModelosController;
use App\Http\Controllers\Api\VistaOrdenController;
use App\Http\Controllers\Api\FRController;
use App\Http\Controllers\Api\DetalleArticulosController;
use App\Http\Controllers\Api\VistaUbicacionArticulosController;
use App\Http\Controllers\Api\VistaDetalleArticuloUbicacionController;
use App\Http\Controllers\Api\MovimientoTraspasoController;
use App\Http\Controllers\Api\MarcasController;
use App\Http\Controllers\Api\CategoriasController;
use App\Http\Controllers\Api\ArticulosController;
use App\Http\Controllers\Api\UnidadMedidaController;
use App\Http\Controllers\Api\PorcentajesController;
use App\Http\Controllers\Api\TipoUsosController;
use App\Http\Controllers\Api\SessionesDespachoController;
/*
|--------------------------------------------------------------------------
| API Rutas

*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});



Route::get('selectOrdenFR/{id_solicitud}', [DetallesComprasController:: class, 'mostrarArticulosFR']);
Route::get('detallesCompras/{id_detalle}', [DetallesComprasController:: class, 'mostrarDetallesCompras']);
Route::get('mostrarDetallesFr/{id_fer_encabe}', [FRController:: class, 'verDetallesFr']);
Route::get('solicitudesFR', [FRController::class, 'mostrarSolicitudFR']);
Route::get('detallesFR',[FRController:: class, 'mostrarFr']);
Route::get('contarNumeroControl', [FRController::class,'contarNumeroControl']);
Route::get('mostrarLocalizacion/{fk_deposito}', [LocalizacionController::class, 'traerLocalizacionesPederteminadas']);
Route::put('cambiar_predeterminado_localizacion',[LocalizacionController::class,'cambiarPredeterminado']);
Route::put('desactivar_localizacion',[LocalizacionController::class,'cambiarInactivo']);
Route::put('activar_localizacion',[LocalizacionController::class,'cambiarActivo']);
Route::get('verificar_existe_localizacion_predeterminada/{fk_despacho}',[LocalizacionController::class,'verificarExisteLocalizacionPredeterminada']);
Route::get('localizacion', [LocalizaArticuloController:: class, 'mostrarLocalizaArticulos']);
Route::get('contarStock', [LocalizaArticuloController:: class, 'mostrarCantidadStock']);
Route::put('editar_localizacion', [LocalizacionController::class, 'editarLocalizacion']);
Route::get('mostrar_localizaciones_para_el_movimiento_despacho_destino/{codigo_despacho}',[LocalizacionController::class,'mostrarLocalizacionesMovimientos']);
Route::get('mostrar_deposito_movimiento_por_localizacion_destino/{id_localizacion}',[LocalizacionController::class,'mostrarDepositoMovimiento']);
Route::get('mostrar_localizaciones_tipo_inventario/{codigo_despacho}',[LocalizacionController::class,'mostrarLocalizacionesDepositoInventario']);
Route::put('editar_deposito',[DepositosController::class,'editarDepositos']);
Route::get('depositos_despachos/{fk_despacho}',[DepositosController::class,'mostrarDespositosDespachos']);
Route::get('detalles_fr_pendientes/{id_fer_encabe}',[FRController::class,'detallesArticulosPendientesFR']);
Route::put('editar_datos_generales_de_fr',[FRController::class,'guardarDatosGenerales']);
Route::put('editar_detalle_fr',[FRController::class,'guadarDetalleArticuloFR']);
Route::get('solicitudes_fr_confirmados/{id_fer_encabe}',[FRController::class,'detallesArticulosCompletadosFR']);
Route::get('listado_fr_confirmados',[FRController::class,'mostrarListaFRCompletos']);
Route::get('verificar_localizacion_existente/{id_fer_localizacion}',[LocalizarFrController::class,'verificarExisteLocalizacion']);
Route::get('verificar_activo_exixtente/{numero_activo}',[DetalleArticulosController::class,'mostrarActivoExiste']);
Route::get('verificar_numero_serie/{numero_serie}',[DetalleArticulosController::class,'mostrarNumeroSerieExiste']);
Route::get('localizaciones_otro_despacho/{codigo_despacho}',[LocalizacionController::class,'localizacionesOtroDespacho']);
Route::get('mis_localizaciones/{codigo_despacho}',[LocalizacionController::class,'misLocalizaciones']);
Route::put('editar_ubicacion_articulos',[UbicacionArticuloController::class,'editarUbicacion']);
Route::get('sumar_cantidad_almacen/{fk_articulo}',[DetallesComprasController::class,'sumarCantidadAlmacen']);
Route::get('frPendientes/{id_fer_encabe}', [FRController:: class, 'mostrarFrPendientes']);
Route::put('confirmar_todo_fr', [FRController:: class, 'confirmarTodoFR']);
Route::put('confirmar_fr_por_localizaciones',[FRController::class,'confirmarFrLocalizacion']);
Route::get('localizaciones_por_fr', [LocalizarFrController:: class, 'mostrarLocalizacionFr']);
Route::put('revertir_fr_completo', [FRController::class, 'revertirFR']);
Route::post('verificar_si_puede_revertir_fr',[FRController::class,'verificarRevertirFR']);
Route::get('traer_localizaciones_por_depositos/{id_deposito}',[LocalizacionController::class,'traerLocalizaciones']);
Route::get('listar_localizaciones_confirmacion_fr/{id_localizacion}',[LocalizacionController::class,'listarDepositosPorLocalizaciones']);
Route::get('mostrar_depositos_x_confirmar_caja_menuda/{fk_solicitado}',[DepositosController::class,'mostrarDepositosCajaMenuda']);
Route::get('depositos_localizacion/{fk_despacho}',[LocalizacionController::class,'mostrarDepositosLocalizacion']);
Route::get('mostrar_localizaciones_confirmar_caja_menuda/{fk_solicitado}',[LocalizacionController::class,'mostrarLocalizacionesCajaMenuda']);
Route::get('mostrar_localizaciones_tipo_despacho/{codigo_despacho}',[LocalizacionController::class,'mostrarLocalizacionesTipoDespacho']);
Route::get('mostrar_localizaciones_tipo_inventario/{codigo_despacho}',[LocalizacionController::class,'mostrarLocalizacionesTipoInventario']);
Route::get('mostrar_depositos_caja_menuda/{id_localizacion}',[LocalizacionController::class,'mostrarDepositosCajaMenuda']);
Route::put('confirmar_todo_sitio',[DetallesComprasController::class,'confirmarTodoSitio']);
Route::get('depositos_localizaciones_predeterminadas',[LocalizacionController::class,'mostrarLocalizacionPrederteminada']); 
Route::get('detalle_historial_fr/{id_fer_encabe}',[FRController::class,'detallesHistorialFR']);
Route::get('localizacion_prederteminada_fr/{id_localizacion}',[LocalizarFrController::class,'mostrarLocalizacionPrederetimadaFR']);
Route::get('mostrar_historial_fr', [FRController::class,'mostrarHistorialFR']);
Route::get('ver_detalles_fr_revertir/{id_fer_encabe}',[FRController::class,'verDetallesFRporRevertir']);
Route::put('cancelar_articulo_fr',[FRController::class,'cancelarArticuloFR']);
Route::put('cancelar_fr',[FRController::class,'cancelarCompletoFR']);
Route::get('verificar_existe_cantidad_recibida_fr/{id_fer_encabe}',[FRController::class,'verificarExisteCantidadRecibidaFR']);
Route::get('datos_solicitantes_generales_fr/{id_fer_encabe}',[FRController::class,'mostrarDatosSolicitantesFR']);
Route::get('mostrar_detalle_movimiento/{id_movimiento_det}',[MovimientosController::class,'mostrarDetalleMovimiento']);
Route::get('verificar_existe_cantidad_stock_ubicacion/{fk_despacho}',[VistaUbicacionArticulosController::class,'verificarExisteCantidadUbicacionDespacho']);
Route::get('buscar_articulos_en_localizacion_por_despacho/{codigo_despacho}',[VistaUbicacionArticulosController::class,'mostrarArticulosLocalizacionDespacho']);
Route::get('articulos_en_localizaciones_de_tipo_deposito_inventario/{codigo_despacho}',[VistaUbicacionArticulosController::class,'mostrarArticulosDepositoInventario']);
Route::get('articulos_en _localizaciones_de_tipo_deposito_despacho/{codigo_despacho}',[VistaUbicacionArticulosController::class,'mostrarArticulosDepositoDespacho']);
Route::get('mostrar_localizaciones_movimiento_de_traspaso_de_entrada/{codigo_despacho}',[VistaUbicacionArticulosController::class,'mostrarArticulosLocalizacionesTipoDespacho']);
Route::get('traer_articulo_por_despacho_de_localizacion/{fk_localizacion}',[VistaUbicacionArticulosController::class,'traerArticuloPorLocalizacion']);
Route::get('mostrar_articulos_en_detalle_de_articulo_por_ubicacion/{id_ubicacion}',[VistaDetalleArticuloUbicacionController::class,'mostrarDetalleArticulosPorUbicacion']);
Route::get('mostrar_traspaso_pendiente',[MovimientoTraspasoController::class,'mostrarTraspasoPendiente']);
Route::get('mostrar_articulos_por_localizacion_por_fr/{id_fer_encabe}', [LocalizarFrController::class,'mostrarLocalizacionArticuloFR']);
Route::get('verificar_existe_ubicacion_origen_detalle_movimiento/{fk_ubicacion_origen}', [VistaUbicacionArticulosController::class,'verificarExisteFK_Ubicacion_Origen']);
Route::get('mostrar_detalle_articulo_por_ubicacion/{id_ubicacion}',[VistaDetalleArticuloUbicacionController::class,'mostrarDetalleArticulo']);
Route::put('editar_color',[ColoresController::class,'editarColores']);
Route::get('verificar_color_existe_detalle_articulo/{id_color}',[ColoresController::class,'verificarColorExisteDetalleArticulo']);
Route::post('verificar_si_existe_color}',[ColoresController::class,'mostrarColorExiste']);
Route::put('editar_detalle_de_articulo',[DetalleArticulosController::class,'editarDetalleArticulo']);
Route::post('verificar_si_existe_activo_registrado',[DetalleArticulosController::class,'verificarActivoExiste']);
Route::post('verificar_si_existe_serie_registrado',[DetalleArticulosController::class,'verificarNumeroSerieExiste']);
Route::get('verificar_si_existe_ubicacion_en_movimineto/{id_ubicacion}',[VistaUbicacionArticulosController::class,'verificarExisteUbicacionMovimineto']);
Route::get('mostrar_movimiento_pendiente_por_detalle/{id_movimiento_enc}',[MovimientoTraspasoController::class,'mostrarTraspasoPendientePorDetalleMovimineto']);
Route::get('mostrar_movimiento_pendiente_por_detalle_de_entrada/{id_movimiento_enc}',[MovimientoTraspasoController::class,'mostrarTraspasoPendientePorDetalleMoviminetoEntrada']);
Route::get('mostrar_movimiento_pendiente_por_detalle_nota_entrada/{id_movimiento_enc}',[MovimientoTraspasoController::class,'mostrarTraspasoPendientePorNota']);
Route::put('eliminar_articulo_movimiento_salida',[MovimientoTraspasoController::class,'eliminarArticuloMovimiento']);
Route::put('eliminar_articulo_de_movimiento',[MovimientoTraspasoController::class,'eliminarArticuloMovimiento']);
Route::put('editar_datos_generales_movimiento',[MovimientoTraspasoController::class,'editarMovimientoGenerales']);
Route::put('editar_datos_generales_nota_salida',[MovimientoTraspasoController::class,'editarMovimientoGeneralesNotaSalida']);
Route::put('editar_detalle_movimiento',[MovimientoTraspasoController::class,'editarMovimientoDetalle']);
Route::put('editar_traspaso_de_nota',[MovimientoTraspasoController::class,'editarTraspasoNota']);
Route::put('cancelar_traspaso_salida',[MovimientoTraspasoController::class,'cancelarTraspasoSalida']);
Route::put('cancelar_traspaso',[MovimientoTraspasoController::class,'cancelarTraspaso']);
Route::put('cancelar_nota_entrega',[MovimientoTraspasoController::class,'cancelarNotaEntrega']);
Route::put('cancelar_traspaso_entrada',[MovimientoTraspasoController::class,'cancelarTraspasoEntrada']);
Route::post('registrar_traspaso_nota_entrega',[MovimientoTraspasoController::class,'RegistrarnotaSalida']);
Route::get('mis_depositos/{codigo_despacho}',[DepositosController::class,'MisDepositos']);
Route::get('depositos_otro_despacho/{codigo_despacho}',[DepositosController::class,'depositosOtroDespacho']);
Route::post('verificar_si_tiene_stock_por_deposito/{id_deposito}',[DepositosController::class,'verificarStockDepositoInventario']);
Route::put('confirmar_traspaso_salida',[MovimientoTraspasoController::class,'confirmarTraspasoSalida']);
Route::put('confirmar_traspaso_entrada',[MovimientoTraspasoController::class,'confirmarTraspasoEntrada']);
Route::put('confirmar_traspaso_de_nota', [MovimientoTraspasoController::class,'confirmarTraspasoNota']);
Route::get('ubicaciones_otro_despacho/{codigo_despacho}',[VistaUbicacionArticulosController::class,'ubicacionesOtroDespacho']);
Route::get('mis_ubicaciones/{codigo_despacho}',[VistaUbicacionArticulosController::class,'misUbicaciones']);
Route::get('articulos_en_cantidad_pedida_global',[VistaArticulosController::class,'aticulosEnCantidadPedidaGlobal']);
Route::get('articulos_cantidad_pedida_global_todos',[VistaArticulosController::class,'articulosCantidadPedida']);
Route::get('mostrar_localizaciones_deposito_tipo_inventario/{fk_solicitado}',[LocalizacionController::class,'mostrar_localizaciones_tipo_deposito_inventario']);
Route::post('login', [LoginController::class, 'selecionarUsuarios']);
Route::get('mostrarPerfil', [LoginController::class, 'index']);
Route::get('mostrar_ordenes_pendientes',[SolicitudCompraController::class,'mostrarSolicitudDeCompraPendiente']);
Route::post('mostrar_orden_compra_existe',[SolicitudCompraController::class,'verificarOrdenCompraExistente']);
Route::post('mostrar_no_notas',[SolicitudCompraController::class,'mostrarNotas']);
Route::post('mostrar_no_caja_menuda',[SolicitudCompraController::class,'mostraCajaMenuda']);
Route::get('detalle_compras_solicitud_compras_pendientes/{id_solicitud}',[SolicitudCompraController::class,'detalle_de_solicitud_de_compras_pendientes']);
Route::get('mostrar_proveedores_activos', [ProveedoresController::class, 'traerProveedor']);
Route::post('verificar_si_existe_proveedor_en_compra/{id_proveedor}',[ProveedoresController::class,'verificarProveedorEnCompra']);
Route::post('verificar_porveedor_para_desactivar/{id_proveedor}',[ProveedoresController::class,'verificarProveedorParaDesactivar']);
Route::put('editar_proveedor',[ProveedoresController::class,'editarProveedor']);
Route::put('desactivar_proveedor',[ProveedoresController::class,'desactivarProveedor']);
Route::put('activar_proveedor',[ProveedoresController::class,'activarProveedor']);
Route::post('verifica_si_el_articulo_tiene_detalle_de_compra/{id_articulo}',[ArticulosController::class,'buscarArticuloEnCompraEditar']);
Route::put('editar_articulo',[ArticulosController::class,'editarArticulos']);
Route::put('editar_marca',[MarcasController::class,'editarMarca']);
Route::post('verificar_si_la_marca_existe_detalle_de_compra/{id_marca}',[MarcasController::class,'verificarMarcaDetalleCompra']);
Route::post('verificar_modelo_existe_detalle_compra/{id_modelo}',[ModelosController::class,'verificarModeloExiteCompra']);
Route::get('selectModelos/{id_marca}', [ModelosController::class, 'mostrarModelos']);
Route::put('editar_modelo',[ModelosController::class,'editarModelo']);
Route::post('verificar_si_existe_categoria_en_compra/{id_categoria}',[CategoriasController::class,'verificarExisteCategoriaCompra']);
Route::put('editar_categoria',[CategoriasController::class,'editarCategoria']);
Route::get('total_solicitud_de_compras',[SolicitudCompraController::class,'totalSolicitudesCompras']);
Route::get('traer_ultimas_dies_compras',[SolicitudCompraController::class,'ultimasSolicitudCompras']);
Route::put('editar_solicitud_orden_de_compra',[SolicitudCompraController::class,'editarSolicitud']);
Route::post('pdf_solicitud_compra/{id_solicitud}',[SolicitudCompraController::class,'datosPDFSolicitudCompra']);
Route::put('cancelar_orden_de_compra',[SolicitudCompraController::class,'cancelarOrdenCompra']);
Route::post('verificar_existe_cantidad_recibida_orden_compra/{id_solicitud}',[SolicitudCompraController::class,'verificarExisteCantidadRecibidaOrdenCompra']);
Route::put('confirmar_toda_la_orden_de_compra_en_almacen',[SolicitudCompraController::class,'confirmarTodoAlmacen']);
Route::put('confirmar_todo_en_sitio',[SolicitudCompraController::class,'confirmarTodoSitio']);
Route::get('cantidad_de_unidades_de_articulos_en_almacen',[ArticulosController::class,'UnidadesEnAlmacen']);
Route::get('cantidad_de_solicitudes_pendientes',[SolicitudCompraController::class,'totalSolicitudesPendientesCompras']);
Route::get('solicitudes_compras_de_mi_despacho',[VistaOrdenController::class,'solicitudesComprasMias']);
Route::get('total_solicitudes_pendientes_mias/{codigo_despacho}',[VistaOrdenController::class,'TotalsolicitudesComprasMiasPendientes']);
Route::get('detalle_de_solicitud_mias/{id_solicitud}',[VistaOrdenController::class,'mostrarDetalleSolicitudMias']);
Route::get('despacho',[DespachoController::class,'traerDespacho']);
Route::get('despacho_destino_por_movimiento/{codigo}',[DespachoController::class,'traerDespachoMovimientoDestino']);
Route::get('despacho_origen_por_movimientos_entrada/{codigo}',[DespachoController::class,'traerDespachoMovimientoOrigenEntrada']);
Route::get('departamentos_de_almacen', [DespachoController:: class, 'traerUnidadAlmacen']);
Route::get('traer_despacho_de_informatica',[DespachoController:: class, 'mostrarDespachoInformatica']); // en movimineto del PDF
Route::get('mostrar_direccion_actual_bienes_patrimoniales',[DespachoController::class,'mostrarDireccionBienesPatrimoniales']);
Route::get('mostrar_despachos',[DespachoController::class,'mostrarConsultaOtroDespacho']);
Route::get('ubicaciones_de_articulos_en_ubicacion',[VistaUbicacionArticulosController::class,'ubicacionesArticulos']);
Route::get('articulos_en_almacen',[VistaArticulosController::class,'articulosEnAlmacen']);
Route::get('detalle_de_articulos_en_almacen/{fk_articulo}',[SolicitudCompraController::class,'traerArticulosEnAlmacenDetalleCompras']);
Route::put('confirmar_global_mixta',[SolicitudCompraController::class,'confirmacionMixtaGlobal']);
Route::put('confirmar_pacial_solicitud',[SolicitudCompraController::class,'ConfirmacionParcial']);
Route::put('cancelar_articulo_compra',[SolicitudCompraController::class,'cancelarArticuloCompra']);
Route::get('cantidad_disponible/{id_detalle}', [SolicitudCompraController::class,'DisponibleAlmacen']);
Route::get('localizacion_prederteminada/{codigo}',[LocalizacionController::class,'localizacionesPrederteminadas']);
Route::post('registrar_caja_menuda',[SolicitudCompraController::class,'registrarCajamenuda']);
Route::get('detalle_de_caja_menuda_pendiente/{id_solicitud}',[SolicitudCompraController::class,'detalle_de_caja_menuda_pendientes']);
Route::put('editar_caja_menuda',[SolicitudCompraController::class,'editarCajaMenuda']);
Route::put('confirmar_caja_menuda',[SolicitudCompraController::class,'confirmarCajaMenuda']);
Route::get('selectGrupos/{id_categoria}', [GruposController:: class, 'mostrarGrupos']);
Route::put('editar_grupo', [GruposController::class, 'editarGrupos']);
Route::get('selectSubGrupos/{id_grupo}', [SubGruposController::class, 'mostrarSubgrupos']);
Route::put('editar_subgrupo', [SubGruposController::class, 'editarSubgrupos']);
Route::put('editar_unidad_medida', [UnidadMedidaController::class, 'editarUnidadMedida']);
Route::put('editarPorcentaje', [PorcentajesController::class,'modificarPorcentaje']);
Route::put('activarPorcentaje',[PorcentajesController::class, 'activarPorcentajes']);
Route::put('desActivar',[PorcentajesController::class,'desactivarPorcentajes']);
Route::get('itbms', [PorcentajesController::class, 'porcentajesActivos']);
Route::get('traer_empleados_bienes_patrimoniales',[EmpleadosController::class,'empleadosBienesPatrimoniales']);
Route::get('traer_empleados_bienes_patrimoniales_destino',[EmpleadosController::class,'empleadosBienesPatrimonialesDestino']);
Route::get('traerEmpleados/{fk_despacho}',[EmpleadosController::class,'mostrarEmpleados']);
Route::get('detalle_de_solicitud_caja_menuda/{id_solicitud}', [SolicitudCompraController::class,'detalle_de_caja_menuda']);
Route::apiResource('sessiones_de_despacho_interna', SessionesDespachoController::class);
Route::apiResource('mostrarTipoUsos', TipoUsosController::class);
Route::apiResource('sub_grupos', SubGruposController::class);
Route::apiResource('grupos',GruposController::class);
Route::apiResource('categorias',CategoriasController::class);
Route::apiResource('marcas',MarcasController::class);
Route::apiResource('proveedores', ProveedoresController::class);
Route::apiResource('articulos', ArticulosController::class);
Route::apiResource('vistasArticulos', VistaArticulosController::class);
Route::apiResource('solicitud_compras', SolicitudCompraController::class);
Route::apiResource('tipo_solicitudes', TipoSolicitudesController::class);
Route::apiResource('localizaciones', LocalizacionController::class);
Route::apiResource('depositos', DepositosController::class);
Route::apiResource('modelos', ModelosController::class);
Route::apiResource('vista_orden_compra', VistaOrdenController::class);
Route::apiResource('fr', FRController::class);
Route::apiResource('detalles_articulos', DetalleArticulosController::class);
Route::apiResource('ubicaciones_articulos',VistaUbicacionArticulosController::class);
Route::apiResource('vista_detalle_articulo_ubicacion', VistaDetalleArticuloUbicacionController::class);
Route::apiResource('movimientos_de_traspasos', MovimientoTraspasoController::class);
Route::apiResource('colores', ColoresController::class);
Route::apiResource('unidad_de_medidas',UnidadMedidaController::class);
Route::apiResource('porcentajes', PorcentajesController::class);



